<?php
$escHtml = $this->plugin('escapeHtml');
$escAttr = $this->plugin('escapeHtmlAttr');

$footerLogo      = $this->themeSetting( 'footer_logo' );
$footerSiteInfo  = $this->themeSetting( 'footer_site_info' );
$footerMenu      = $this->themeSetting( 'footer_menu' );
$footerMenuDepth = (int) $this->themeSetting('footer_menu_depth') ? (int) $this->themeSetting('footer_menu_depth') -1 : -1;
$footerContent   = $this->themeSetting( 'footer_content' );
$socialNetworks  = array( 'facebook', 'twitter', 'linkedin', 'instagram', 'youtube', 'mastodon' );

$additional_classes = '';

if ( ! $footerMenu ) {
	$additional_classes .= ' no-menu';
} elseif ( ! $footerLogo && ! $footerSiteInfo && ! $footerContent ) {
	$additional_classes .= ' menu-only';
}

if ( $footerMenu && ( $footerLogo || $footerSiteInfo ) && $footerContent ) {
	$additional_classes .= ' all-columns';

	if ( $footerMenuDepth > 1 ) {
		$additional_classes .= ' menu-depth-2';
	}
}

$hasSocialNetworks = false;

foreach ( $socialNetworks as $social_network ) {
	if ( $this->themeSetting( "{$social_network}_url" ) ) {
		$hasSocialNetworks = true;
		break;
	}
}
?>

<footer class="main-footer">

	<!-- Footer Top -->
	<?php if ( $footerLogo || $footerSiteInfo || $footerMenu || $footerContent ): ?>
		<div class="main-footer__top">
			<div class="container main-footer__top-container <?php echo $additional_classes; ?>">

				<!-- Column 1 -->
				<?php if ( $footerLogo || $footerSiteInfo ) : ?>

					<div class="main-footer__col1">
						<?php if ( $footerLogo ): ?>
							<img
								src="<?php echo $this->themeSettingAssetUrl( 'footer_logo' ); ?>"
								alt="<?php echo $escHtml( $site->title() ); ?>"
								style="<?php echo $footerSiteInfo ? 'margin-bottom: 30px;' : ''; ?>" />
						<?php endif; ?>

						<div class="footer_site_info">
							<?php if ( $footerSiteInfo ) : ?>
								<?php echo $footerSiteInfo; ?>
							<?php endif; ?>
						</div>
					</div>
					
				<?php endif; ?>

				<!-- Column 2 -->
				<?php if ( $footerMenu ) : ?>
				
					<div class="main-footer__col2">
						<?php
							echo $site->publicNav()->menu()->renderMenu(null, [
								'maxDepth' => $footerMenuDepth
							]);
						?>
					</div>

				<?php endif; ?>

				<!-- Column 3 -->
				<?php if ( $footerContent ) : ?>

					<div class="main-footer__col3">
						<?php if ( $footerContent ) : ?>
							<?php echo $footerContent; ?>
						<?php endif; ?>
					</div>

				<?php endif; ?>

			</div>
		</div>
	<?php endif; ?>

	<!-- Footer Bottom -->
	<div class="main-footer__bottom">
		<div class="container main-footer__bottom-container <?php echo $hasSocialNetworks ? 'has-social-networks' : ''; ?>">

			<!-- Social Networks -->
			<?php if ($hasSocialNetworks) : ?>
				<div class="main-footer__social-network">
					<?php foreach ( $socialNetworks as $social_network ) : ?>
						<?php if ( $social_network_url = $this->themeSetting( "{$social_network}_url" ) ) : ?>
							<a href="<?php echo $escAttr($social_network_url); ?>">
								<img src="<?php echo $this->assetUrl( "img/{$social_network}.svg" ); ?>"
									alt="<?php echo $escAttr( $social_network ); ?>">
							</a>
						<?php endif; ?>
					<?php endforeach; ?>
				</div>
			<?php endif; ?>

			<!-- Copyright -->
			<div class="main-footer__copyright">
				<?php if ( $footer_copyright = $this->themeSetting( 'footer_copyright' ) ) : ?>
					<?php echo $footer_copyright; ?>
				<?php else: ?>
					<?php echo $this->translate( 'Powered by Omeka S' ); ?>
				<?php endif; ?>
			</div>
		</div>
	</div>

</footer>
