<?php
$translate = $this->plugin('translate');
$navDepth = (int) $this->themeSetting('nav_depth') ? (int) $this->themeSetting('nav_depth') -1 : -1;
?>

<header class="main-header">

	<?php echo $userBar; ?>

	<div class="main-header__top-bar container">
		<a class="main-header__advanced-search" href="<?php echo $site->url() . '/item/search'; ?>"><?php echo $translate('Advanced search'); ?></a>
		<div class="main-header__search-form">
			<?php echo $this->partial('common/search-form'); ?>
		</div>
	</div>
	<hr class="alignfull">

	<div class="main-header__main-bar container">
		<h1 class="main-header__site-title site-title">
			<a href="<?php echo $site->url(); ?>">
			<?php if ($this->themeSetting('logo')): ?>
				<img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $this->escapeHtml( $site->title() ); ?>" />
			<?php else: ?>
				<?php echo $this->escapeHtml( $site->title() ); ?>
			<?php endif; ?>
			</a>
		</h1>

		<nav class="main-navigation">
			<div class="main-navigation__container">
				<?php
				echo $site->publicNav()->menu()->renderMenu(null, [
					'addClassToListItem' => true,
					'maxDepth' => $navDepth
				]);
				?>
			</div>
			<div class="main-navigation__toggle"
				 tabindex="0"
				 role="button"
				 aria-expanded="false"
				 aria-controls="menu-drawer"
				 aria-labelledby="menu-backer">
				<span></span>
				<span></span>
				<span></span>
			</div>
		</nav>

		<?php echo $this->partial('common/menu-drawer'); ?>
	</div>

</header>
