<div class="main-header">

	<div class="main-header__top-bar">
		<a href="#">Advanced Search</a>
		<div id="search">
			<?php echo $this->partial('common/search-form'); ?>
		</div>
	</div>

	<div class="main-header__main-bar">
		<h1 class="main-header__site-title">
			<a href="<?php echo $site->url(); ?>">
			<?php if ($this->themeSetting('logo')): ?>
				<img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $this->escapeHtml($siteTitle); ?>" />
			<?php else: ?>
				<?php echo $this->escapeHtml( $site->title() ); ?>
			<?php endif; ?>
			</a>
		</h1>

		<nav class="main-nav">
			<?php
			echo $site->publicNav()->menu()->renderMenu(null, [
				'maxDepth' => $this->themeSetting('nav_depth') - 1
			]);
			?>
		</nav>
	</div>

</div>
