<?php
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap');
$this->headLink()->prependStylesheet('https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,400;0,700;1,400;1,700&display=swap');
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$headerLayout = ($this->themeSetting('header_layout')) ? $this->themeSetting('header_layout') : 'left';
$banner = $this->themeSettingAssetUrl('banner');
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_','-', $this->themeSetting('banner_position')) : 'center';
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>
		
		<style>
			<?php if ($accentColor = $this->themeSetting('accent_color')): ?>
			a:link,
			a:visited {
				color: <?php echo $accentColor; ?>
			}
			
			a:active,
			a:hover {
				color: <?php echo $accentColor; ?>;
				opacity: .75;
			}
			<?php endif; ?>

			.banner {
				height: <?php echo ($bannerHeight !== '') ? $bannerHeight: 'auto'  ?>;
				align-items: <?php echo $bannerPosition; ?>;
			}
			<?php if ($bannerHeightMobile !== ''): ?>
				@media screen and (max-width:640px) {
					.banner {
						height: <?php echo $bannerHeightMobile; ?>;
					}
				}
			<?php endif; ?>
		</style>
	</head>

	<?php echo $this->htmlElement('body'); ?>
		<a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
		<?php echo $userBar; ?>
		<header>
			<?php if ($headerLayout == 'left'): ?>
				<?php echo $this->partial('common/header-left'); ?>
			<?php else: ?>
				<?php echo $this->partial('common/header-center'); ?>
			<?php endif; ?>
		</header>
		<?php if ($banner): ?>
		<div class="banner">
			<img src="<?php echo $this->themeSettingAssetUrl('banner'); ?>" title="Banner">
		</div>
		<?php endif; ?>
		<div id="content" role="main">
			<?php echo $this->content; ?>
		</div>
		<footer>
			<?php if ($footerContent = $this->themeSetting('footer')): ?>
			<?php echo $footerContent; ?>
			<?php else: ?>
				<?php echo $this->translate('Powered by Omeka S'); ?>
			<?php endif; ?>
		</footer>
	</body>
</html>
